type: sgd
lr: 1e-2
momentum: 0.9
weight_decay: 1e-4

search_space:
  lr: { low: 1e-3, high: 1e-1, log: True }
  momentum: { low: 0.8, high: 0.99 }
  weight_decay: { low: 1e-5, high: 1e-3, log: True }
