type: transfer
backbone: densenet161
pretrained: true
num_classes: 101

freeze_backbone: false
fine_tune_from_layer: denseblock3
fc_hidden_size: 256
dropout_rate: 0.3
lr_multiplier_backbone: 0.05

search_space:
  freeze_backbone: [false]
  fine_tune_from_layer: [denseblock3, denseblock4, none]
  fc_hidden_size: { low: 128, high: 512 }
  dropout_rate: { low: 0.1, high: 0.5 }
  lr_multiplier_backbone: { low: 0.005, high: 1.0 }
