type: transfer
backbone: mobilenet_v3_small
pretrained: true
num_classes: 101

freeze_backbone: false
fine_tune_from_layer: features.10
fc_hidden_size: 256
dropout_rate: 0.3
lr_multiplier_backbone: 0.1

search_space:
  freeze_backbone: [true, false]
  fine_tune_from_layer: [features.8, features.10, none]
  fc_hidden_size: { low: 128, high: 512 }
  dropout_rate: { low: 0.1, high: 0.5 }
  lr_multiplier_backbone: { low: 0.005, high: 1.0 }
