n_trials: 20
direction: maximize
metric: accuracy
study_name: food101_study
storage: sqlite:///results/optuna_results.db
pruner:
  type: median
  n_startup_trials: 5
  n_warmup_steps: 5
sampler:
  type: tpe
